### ISSUE TITLE
Last Modified Date does not update in table of patients

### ISSUE THREAD

**Issue by hari387** [DrDocx/DrDocx-Electron2#31]
Modifying a patient does not update the "last modified column" in the patients table, as seen below:

![image](https://user-images.githubusercontent.com/20744112/85971945-62f06f00-b983-11ea-9519-0df07dbc7786.png)
![image](https://user-images.githubusercontent.com/20744112/85971967-7d2a4d00-b983-11ea-8e0c-94b39231e8ab.png)
![image](https://user-images.githubusercontent.com/20744112/85971945-62f06f00-b983-11ea-9519-0df07dbc7786.png)

**Comment by ProbablyFaiz** [comment]
This was a backend bug, fixed via [fee16e1f](https://github.com/DrDocx/DrDocx-Master/commit/fee16e1f6b70adcdfe1b3f2a7785234c97d4568f).
